/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CustomersIdRouteImport } from './routes/customers.$id'
import { Route as CustomersNewRouteImport } from './routes/customers.new'
import { Route as MenuIdRouteImport } from './routes/menu.$id'
import { Route as MenuNewRouteImport } from './routes/menu.new'
import { Route as CustomersIdEditRouteImport } from './routes/customers.$id.edit'
import { Route as MenuIdEditRouteImport } from './routes/menu.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIdRoute = CustomersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CustomersRoute,
} as any)
const CustomersNewRoute = CustomersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CustomersRoute,
} as any)
const MenuIdRoute = MenuIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MenuRoute,
} as any)
const MenuNewRoute = MenuNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MenuRoute,
} as any)
const CustomersIdEditRoute = CustomersIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CustomersIdRoute,
} as any)
const MenuIdEditRoute = MenuIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => MenuIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/menu': typeof MenuRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/menu/$id': typeof MenuIdRouteWithChildren
  '/menu/new': typeof MenuNewRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/menu/$id/edit': typeof MenuIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/menu': typeof MenuRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/menu/$id': typeof MenuIdRouteWithChildren
  '/menu/new': typeof MenuNewRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/menu/$id/edit': typeof MenuIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers': typeof CustomersRouteWithChildren
  '/menu': typeof MenuRouteWithChildren
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/customers/$id': typeof CustomersIdRouteWithChildren
  '/customers/new': typeof CustomersNewRoute
  '/menu/$id': typeof MenuIdRouteWithChildren
  '/menu/new': typeof MenuNewRoute
  '/customers/$id/edit': typeof CustomersIdEditRoute
  '/menu/$id/edit': typeof MenuIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/menu/$id'
    | '/menu/new'
    | '/customers/$id/edit'
    | '/menu/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/menu/$id'
    | '/menu/new'
    | '/customers/$id/edit'
    | '/menu/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/customers'
    | '/menu'
    | '/reports'
    | '/settings'
    | '/customers/$id'
    | '/customers/new'
    | '/menu/$id'
    | '/menu/new'
    | '/customers/$id/edit'
    | '/menu/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersRoute: typeof CustomersRouteWithChildren
  MenuRoute: typeof MenuRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$id': {
      id: '/customers/$id'
      path: '/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof CustomersIdRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/customers/new': {
      id: '/customers/new'
      path: '/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof CustomersNewRouteImport
      parentRoute: typeof CustomersRoute
    }
    '/menu/$id': {
      id: '/menu/$id'
      path: '/$id'
      fullPath: '/menu/$id'
      preLoaderRoute: typeof MenuIdRouteImport
      parentRoute: typeof MenuRoute
    }
    '/menu/new': {
      id: '/menu/new'
      path: '/new'
      fullPath: '/menu/new'
      preLoaderRoute: typeof MenuNewRouteImport
      parentRoute: typeof MenuRoute
    }
    '/customers/$id/edit': {
      id: '/customers/$id/edit'
      path: '/edit'
      fullPath: '/customers/$id/edit'
      preLoaderRoute: typeof CustomersIdEditRouteImport
      parentRoute: typeof CustomersIdRoute
    }
    '/menu/$id/edit': {
      id: '/menu/$id/edit'
      path: '/edit'
      fullPath: '/menu/$id/edit'
      preLoaderRoute: typeof MenuIdEditRouteImport
      parentRoute: typeof MenuIdRoute
    }
  }
}

interface CustomersIdRouteChildren {
  CustomersIdEditRoute: typeof CustomersIdEditRoute
}

const CustomersIdRouteChildren: CustomersIdRouteChildren = {
  CustomersIdEditRoute: CustomersIdEditRoute,
}

const CustomersIdRouteWithChildren = CustomersIdRoute._addFileChildren(
  CustomersIdRouteChildren,
)

interface CustomersRouteChildren {
  CustomersIdRoute: typeof CustomersIdRouteWithChildren
  CustomersNewRoute: typeof CustomersNewRoute
}

const CustomersRouteChildren: CustomersRouteChildren = {
  CustomersIdRoute: CustomersIdRouteWithChildren,
  CustomersNewRoute: CustomersNewRoute,
}

const CustomersRouteWithChildren = CustomersRoute._addFileChildren(
  CustomersRouteChildren,
)

interface MenuIdRouteChildren {
  MenuIdEditRoute: typeof MenuIdEditRoute
}

const MenuIdRouteChildren: MenuIdRouteChildren = {
  MenuIdEditRoute: MenuIdEditRoute,
}

const MenuIdRouteWithChildren =
  MenuIdRoute._addFileChildren(MenuIdRouteChildren)

interface MenuRouteChildren {
  MenuIdRoute: typeof MenuIdRouteWithChildren
  MenuNewRoute: typeof MenuNewRoute
}

const MenuRouteChildren: MenuRouteChildren = {
  MenuIdRoute: MenuIdRouteWithChildren,
  MenuNewRoute: MenuNewRoute,
}

const MenuRouteWithChildren = MenuRoute._addFileChildren(MenuRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersRoute: CustomersRouteWithChildren,
  MenuRoute: MenuRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
