/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as QuotesRouteImport } from './routes/quotes'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubscribersRouteImport } from './routes/subscribers'
import { Route as TextWidgetsRouteImport } from './routes/text-widgets'
import { Route as CategoriesNewRouteImport } from './routes/categories.new'
import { Route as ContactsIdRouteImport } from './routes/contacts.$id'
import { Route as GalleryIdRouteImport } from './routes/gallery.$id'
import { Route as GalleryNewRouteImport } from './routes/gallery.new'
import { Route as PostsIdRouteImport } from './routes/posts.$id'
import { Route as PostsNewRouteImport } from './routes/posts.new'
import { Route as QuotesIdRouteImport } from './routes/quotes.$id'
import { Route as SubscribersIdRouteImport } from './routes/subscribers.$id'
import { Route as TextWidgetsIdRouteImport } from './routes/text-widgets.$id'
import { Route as TextWidgetsNewRouteImport } from './routes/text-widgets.new'
import { Route as CategoriesIdEditRouteImport } from './routes/categories.$id.edit'
import { Route as GalleryIdEditRouteImport } from './routes/gallery.$id.edit'
import { Route as PostsIdEditRouteImport } from './routes/posts.$id.edit'
import { Route as TextWidgetsIdEditRouteImport } from './routes/text-widgets.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const QuotesRoute = QuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscribersRoute = SubscribersRouteImport.update({
  id: '/subscribers',
  path: '/subscribers',
  getParentRoute: () => rootRouteImport,
} as any)
const TextWidgetsRoute = TextWidgetsRouteImport.update({
  id: '/text-widgets',
  path: '/text-widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CategoriesRoute,
} as any)
const ContactsIdRoute = ContactsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ContactsRoute,
} as any)
const GalleryIdRoute = GalleryIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => GalleryRoute,
} as any)
const GalleryNewRoute = GalleryNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => GalleryRoute,
} as any)
const PostsIdRoute = PostsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PostsRoute,
} as any)
const PostsNewRoute = PostsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PostsRoute,
} as any)
const QuotesIdRoute = QuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => QuotesRoute,
} as any)
const SubscribersIdRoute = SubscribersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => SubscribersRoute,
} as any)
const TextWidgetsIdRoute = TextWidgetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TextWidgetsRoute,
} as any)
const TextWidgetsNewRoute = TextWidgetsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TextWidgetsRoute,
} as any)
const CategoriesIdEditRoute = CategoriesIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => CategoriesRoute,
} as any)
const GalleryIdEditRoute = GalleryIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => GalleryIdRoute,
} as any)
const PostsIdEditRoute = PostsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PostsIdRoute,
} as any)
const TextWidgetsIdEditRoute = TextWidgetsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TextWidgetsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/text-widgets': typeof TextWidgetsRouteWithChildren
  '/categories/new': typeof CategoriesNewRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/gallery/$id': typeof GalleryIdRouteWithChildren
  '/gallery/new': typeof GalleryNewRoute
  '/posts/$id': typeof PostsIdRouteWithChildren
  '/posts/new': typeof PostsNewRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
  '/text-widgets/$id': typeof TextWidgetsIdRouteWithChildren
  '/text-widgets/new': typeof TextWidgetsNewRoute
  '/categories/$id/edit': typeof CategoriesIdEditRoute
  '/gallery/$id/edit': typeof GalleryIdEditRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/text-widgets/$id/edit': typeof TextWidgetsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/text-widgets': typeof TextWidgetsRouteWithChildren
  '/categories/new': typeof CategoriesNewRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/gallery/$id': typeof GalleryIdRouteWithChildren
  '/gallery/new': typeof GalleryNewRoute
  '/posts/$id': typeof PostsIdRouteWithChildren
  '/posts/new': typeof PostsNewRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
  '/text-widgets/$id': typeof TextWidgetsIdRouteWithChildren
  '/text-widgets/new': typeof TextWidgetsNewRoute
  '/categories/$id/edit': typeof CategoriesIdEditRoute
  '/gallery/$id/edit': typeof GalleryIdEditRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/text-widgets/$id/edit': typeof TextWidgetsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/categories': typeof CategoriesRouteWithChildren
  '/contacts': typeof ContactsRouteWithChildren
  '/gallery': typeof GalleryRouteWithChildren
  '/posts': typeof PostsRouteWithChildren
  '/quotes': typeof QuotesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/subscribers': typeof SubscribersRouteWithChildren
  '/text-widgets': typeof TextWidgetsRouteWithChildren
  '/categories/new': typeof CategoriesNewRoute
  '/contacts/$id': typeof ContactsIdRoute
  '/gallery/$id': typeof GalleryIdRouteWithChildren
  '/gallery/new': typeof GalleryNewRoute
  '/posts/$id': typeof PostsIdRouteWithChildren
  '/posts/new': typeof PostsNewRoute
  '/quotes/$id': typeof QuotesIdRoute
  '/subscribers/$id': typeof SubscribersIdRoute
  '/text-widgets/$id': typeof TextWidgetsIdRouteWithChildren
  '/text-widgets/new': typeof TextWidgetsNewRoute
  '/categories/$id/edit': typeof CategoriesIdEditRoute
  '/gallery/$id/edit': typeof GalleryIdEditRoute
  '/posts/$id/edit': typeof PostsIdEditRoute
  '/text-widgets/$id/edit': typeof TextWidgetsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/contacts'
    | '/gallery'
    | '/posts'
    | '/quotes'
    | '/settings'
    | '/subscribers'
    | '/text-widgets'
    | '/categories/new'
    | '/contacts/$id'
    | '/gallery/$id'
    | '/gallery/new'
    | '/posts/$id'
    | '/posts/new'
    | '/quotes/$id'
    | '/subscribers/$id'
    | '/text-widgets/$id'
    | '/text-widgets/new'
    | '/categories/$id/edit'
    | '/gallery/$id/edit'
    | '/posts/$id/edit'
    | '/text-widgets/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/contacts'
    | '/gallery'
    | '/posts'
    | '/quotes'
    | '/settings'
    | '/subscribers'
    | '/text-widgets'
    | '/categories/new'
    | '/contacts/$id'
    | '/gallery/$id'
    | '/gallery/new'
    | '/posts/$id'
    | '/posts/new'
    | '/quotes/$id'
    | '/subscribers/$id'
    | '/text-widgets/$id'
    | '/text-widgets/new'
    | '/categories/$id/edit'
    | '/gallery/$id/edit'
    | '/posts/$id/edit'
    | '/text-widgets/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/categories'
    | '/contacts'
    | '/gallery'
    | '/posts'
    | '/quotes'
    | '/settings'
    | '/subscribers'
    | '/text-widgets'
    | '/categories/new'
    | '/contacts/$id'
    | '/gallery/$id'
    | '/gallery/new'
    | '/posts/$id'
    | '/posts/new'
    | '/quotes/$id'
    | '/subscribers/$id'
    | '/text-widgets/$id'
    | '/text-widgets/new'
    | '/categories/$id/edit'
    | '/gallery/$id/edit'
    | '/posts/$id/edit'
    | '/text-widgets/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CategoriesRoute: typeof CategoriesRouteWithChildren
  ContactsRoute: typeof ContactsRouteWithChildren
  GalleryRoute: typeof GalleryRouteWithChildren
  PostsRoute: typeof PostsRouteWithChildren
  QuotesRoute: typeof QuotesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SubscribersRoute: typeof SubscribersRouteWithChildren
  TextWidgetsRoute: typeof TextWidgetsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quotes': {
      id: '/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof QuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscribers': {
      id: '/subscribers'
      path: '/subscribers'
      fullPath: '/subscribers'
      preLoaderRoute: typeof SubscribersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/text-widgets': {
      id: '/text-widgets'
      path: '/text-widgets'
      fullPath: '/text-widgets'
      preLoaderRoute: typeof TextWidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/new': {
      id: '/categories/new'
      path: '/new'
      fullPath: '/categories/new'
      preLoaderRoute: typeof CategoriesNewRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/contacts/$id': {
      id: '/contacts/$id'
      path: '/$id'
      fullPath: '/contacts/$id'
      preLoaderRoute: typeof ContactsIdRouteImport
      parentRoute: typeof ContactsRoute
    }
    '/gallery/$id': {
      id: '/gallery/$id'
      path: '/$id'
      fullPath: '/gallery/$id'
      preLoaderRoute: typeof GalleryIdRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/gallery/new': {
      id: '/gallery/new'
      path: '/new'
      fullPath: '/gallery/new'
      preLoaderRoute: typeof GalleryNewRouteImport
      parentRoute: typeof GalleryRoute
    }
    '/posts/$id': {
      id: '/posts/$id'
      path: '/$id'
      fullPath: '/posts/$id'
      preLoaderRoute: typeof PostsIdRouteImport
      parentRoute: typeof PostsRoute
    }
    '/posts/new': {
      id: '/posts/new'
      path: '/new'
      fullPath: '/posts/new'
      preLoaderRoute: typeof PostsNewRouteImport
      parentRoute: typeof PostsRoute
    }
    '/quotes/$id': {
      id: '/quotes/$id'
      path: '/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof QuotesIdRouteImport
      parentRoute: typeof QuotesRoute
    }
    '/subscribers/$id': {
      id: '/subscribers/$id'
      path: '/$id'
      fullPath: '/subscribers/$id'
      preLoaderRoute: typeof SubscribersIdRouteImport
      parentRoute: typeof SubscribersRoute
    }
    '/text-widgets/$id': {
      id: '/text-widgets/$id'
      path: '/$id'
      fullPath: '/text-widgets/$id'
      preLoaderRoute: typeof TextWidgetsIdRouteImport
      parentRoute: typeof TextWidgetsRoute
    }
    '/text-widgets/new': {
      id: '/text-widgets/new'
      path: '/new'
      fullPath: '/text-widgets/new'
      preLoaderRoute: typeof TextWidgetsNewRouteImport
      parentRoute: typeof TextWidgetsRoute
    }
    '/categories/$id/edit': {
      id: '/categories/$id/edit'
      path: '/$id/edit'
      fullPath: '/categories/$id/edit'
      preLoaderRoute: typeof CategoriesIdEditRouteImport
      parentRoute: typeof CategoriesRoute
    }
    '/gallery/$id/edit': {
      id: '/gallery/$id/edit'
      path: '/edit'
      fullPath: '/gallery/$id/edit'
      preLoaderRoute: typeof GalleryIdEditRouteImport
      parentRoute: typeof GalleryIdRoute
    }
    '/posts/$id/edit': {
      id: '/posts/$id/edit'
      path: '/edit'
      fullPath: '/posts/$id/edit'
      preLoaderRoute: typeof PostsIdEditRouteImport
      parentRoute: typeof PostsIdRoute
    }
    '/text-widgets/$id/edit': {
      id: '/text-widgets/$id/edit'
      path: '/edit'
      fullPath: '/text-widgets/$id/edit'
      preLoaderRoute: typeof TextWidgetsIdEditRouteImport
      parentRoute: typeof TextWidgetsIdRoute
    }
  }
}

interface CategoriesRouteChildren {
  CategoriesNewRoute: typeof CategoriesNewRoute
  CategoriesIdEditRoute: typeof CategoriesIdEditRoute
}

const CategoriesRouteChildren: CategoriesRouteChildren = {
  CategoriesNewRoute: CategoriesNewRoute,
  CategoriesIdEditRoute: CategoriesIdEditRoute,
}

const CategoriesRouteWithChildren = CategoriesRoute._addFileChildren(
  CategoriesRouteChildren,
)

interface ContactsRouteChildren {
  ContactsIdRoute: typeof ContactsIdRoute
}

const ContactsRouteChildren: ContactsRouteChildren = {
  ContactsIdRoute: ContactsIdRoute,
}

const ContactsRouteWithChildren = ContactsRoute._addFileChildren(
  ContactsRouteChildren,
)

interface GalleryIdRouteChildren {
  GalleryIdEditRoute: typeof GalleryIdEditRoute
}

const GalleryIdRouteChildren: GalleryIdRouteChildren = {
  GalleryIdEditRoute: GalleryIdEditRoute,
}

const GalleryIdRouteWithChildren = GalleryIdRoute._addFileChildren(
  GalleryIdRouteChildren,
)

interface GalleryRouteChildren {
  GalleryIdRoute: typeof GalleryIdRouteWithChildren
  GalleryNewRoute: typeof GalleryNewRoute
}

const GalleryRouteChildren: GalleryRouteChildren = {
  GalleryIdRoute: GalleryIdRouteWithChildren,
  GalleryNewRoute: GalleryNewRoute,
}

const GalleryRouteWithChildren =
  GalleryRoute._addFileChildren(GalleryRouteChildren)

interface PostsIdRouteChildren {
  PostsIdEditRoute: typeof PostsIdEditRoute
}

const PostsIdRouteChildren: PostsIdRouteChildren = {
  PostsIdEditRoute: PostsIdEditRoute,
}

const PostsIdRouteWithChildren =
  PostsIdRoute._addFileChildren(PostsIdRouteChildren)

interface PostsRouteChildren {
  PostsIdRoute: typeof PostsIdRouteWithChildren
  PostsNewRoute: typeof PostsNewRoute
}

const PostsRouteChildren: PostsRouteChildren = {
  PostsIdRoute: PostsIdRouteWithChildren,
  PostsNewRoute: PostsNewRoute,
}

const PostsRouteWithChildren = PostsRoute._addFileChildren(PostsRouteChildren)

interface QuotesRouteChildren {
  QuotesIdRoute: typeof QuotesIdRoute
}

const QuotesRouteChildren: QuotesRouteChildren = {
  QuotesIdRoute: QuotesIdRoute,
}

const QuotesRouteWithChildren =
  QuotesRoute._addFileChildren(QuotesRouteChildren)

interface SubscribersRouteChildren {
  SubscribersIdRoute: typeof SubscribersIdRoute
}

const SubscribersRouteChildren: SubscribersRouteChildren = {
  SubscribersIdRoute: SubscribersIdRoute,
}

const SubscribersRouteWithChildren = SubscribersRoute._addFileChildren(
  SubscribersRouteChildren,
)

interface TextWidgetsIdRouteChildren {
  TextWidgetsIdEditRoute: typeof TextWidgetsIdEditRoute
}

const TextWidgetsIdRouteChildren: TextWidgetsIdRouteChildren = {
  TextWidgetsIdEditRoute: TextWidgetsIdEditRoute,
}

const TextWidgetsIdRouteWithChildren = TextWidgetsIdRoute._addFileChildren(
  TextWidgetsIdRouteChildren,
)

interface TextWidgetsRouteChildren {
  TextWidgetsIdRoute: typeof TextWidgetsIdRouteWithChildren
  TextWidgetsNewRoute: typeof TextWidgetsNewRoute
}

const TextWidgetsRouteChildren: TextWidgetsRouteChildren = {
  TextWidgetsIdRoute: TextWidgetsIdRouteWithChildren,
  TextWidgetsNewRoute: TextWidgetsNewRoute,
}

const TextWidgetsRouteWithChildren = TextWidgetsRoute._addFileChildren(
  TextWidgetsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CategoriesRoute: CategoriesRouteWithChildren,
  ContactsRoute: ContactsRouteWithChildren,
  GalleryRoute: GalleryRouteWithChildren,
  PostsRoute: PostsRouteWithChildren,
  QuotesRoute: QuotesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SubscribersRoute: SubscribersRouteWithChildren,
  TextWidgetsRoute: TextWidgetsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
