'use client';

import Link from 'next/link';

export default function PrivacyPage() {
    return (
        <>
            <section className="page-header">
                <div
                    className="page-header__bg"
                    style={{
                        backgroundImage:
                            'url(/assets/images/backgrounds/page-header-bg-1-1.jpg)',
                    }}
                ></div>
                <div className="container">
                    <h2 className="page-header__title">Privacy Policy</h2>
                    <ul className="garlon-breadcrumb list-unstyled">
                        <li>
                            <Link href="/">Home</Link>
                        </li>
                        <li>
                            <span>Privacy</span>
                        </li>
                    </ul>
                </div>
            </section>

            <section className="blog-details section-space">
                <div className="container">
                    <div className="row justify-content-center">
                        <div className="col-lg-10">
                            <div className="blog-details__text">
                                <p>
                                    <strong>
                                        Fun Farming Uganda (&ldquo;we&rdquo;,
                                        &ldquo;us&rdquo;, or &ldquo;our&rdquo;)
                                        operates the website
                                        funfarminguganda.com and provides
                                        agro-tourism, team-building, and farm
                                        experience services. This page informs
                                        you of our policies regarding the
                                        collection, use, and disclosure of
                                        personal data when you use our services.
                                    </strong>
                                </p>

                                <h2>Definitions</h2>
                                <p>
                                    <strong>Personal Data</strong> means data
                                    about a living individual who can be
                                    identified from those data (or from those
                                    and other information either in our
                                    possession or likely to come into our
                                    possession).
                                </p>
                                <p>
                                    <strong>Usage Data</strong> is data
                                    collected automatically, either generated by
                                    the use of the service or from the service
                                    infrastructure itself (for example, the
                                    duration of a page visit).
                                </p>
                                <p>
                                    <strong>Cookies</strong> are small pieces of
                                    data stored on your device (computer or
                                    mobile device).
                                </p>
                                <p>
                                    <strong>Data Controller</strong> means Fun
                                    Farming Uganda, which determines the
                                    purposes and means of the processing of your
                                    personal data.
                                </p>

                                <h2>Data Collection</h2>
                                <p>
                                    We collect several different types of
                                    information for various purposes to provide
                                    and improve our service to you.
                                </p>
                                <p>
                                    <strong>Personal Data:</strong> While using
                                    our service, we may ask you to provide us
                                    with certain personally identifiable
                                    information that can be used to contact or
                                    identify you. This includes your name, email
                                    address, phone number, physical address, and
                                    booking preferences.
                                </p>
                                <p>
                                    <strong>Usage Data:</strong> We may also
                                    collect information on how the service is
                                    accessed and used. This Usage Data may
                                    include your computer&apos;s Internet
                                    Protocol address (IP address), browser type,
                                    browser version, the pages of our service
                                    that you visit, the time and date of your
                                    visit, the time spent on those pages, unique
                                    device identifiers, and other diagnostic
                                    data.
                                </p>
                                <p>
                                    <strong>Cookies:</strong> We use cookies and
                                    similar tracking technologies to track the
                                    activity on our service and hold certain
                                    information. Cookies are files with a small
                                    amount of data which may include an
                                    anonymous unique identifier. You can
                                    instruct your browser to refuse all cookies
                                    or to indicate when a cookie is being sent.
                                </p>

                                <h2>Use of Data</h2>
                                <p>
                                    Fun Farming Uganda uses the collected data
                                    for the following purposes:
                                </p>
                                <ul>
                                    <li>
                                        To provide and maintain our service,
                                        including to monitor the usage of our
                                        service
                                    </li>
                                    <li>
                                        To manage your bookings and
                                        reservations for farm activities and
                                        events
                                    </li>
                                    <li>
                                        To contact you with administrative
                                        information, booking confirmations, and
                                        updates
                                    </li>
                                    <li>
                                        To provide customer support and respond
                                        to your inquiries
                                    </li>
                                    <li>
                                        To gather analysis or valuable
                                        information so that we can improve our
                                        service
                                    </li>
                                    <li>
                                        To detect, prevent, and address
                                        technical issues
                                    </li>
                                    <li>
                                        To send you marketing communications
                                        (with your consent)
                                    </li>
                                </ul>

                                <h2>Data Retention</h2>
                                <p>
                                    Fun Farming Uganda will retain your Personal
                                    Data only for as long as is necessary for the
                                    purposes set out in this Privacy Policy. We
                                    will retain and use your Personal Data to
                                    the extent necessary to comply with our
                                    legal obligations (for example, if we are
                                    required to retain your data to comply with
                                    applicable laws), resolve disputes, and
                                    enforce our legal agreements and policies.
                                </p>
                                <p>
                                    Usage Data is generally retained for a
                                    shorter period, except when this data is
                                    used to strengthen the security or to
                                    improve the functionality of our service, or
                                    we are legally obligated to retain this data
                                    for longer periods.
                                </p>

                                <h2>Data Transfer</h2>
                                <p>
                                    Your information, including Personal Data,
                                    may be transferred to and maintained on
                                    computers located outside of your state,
                                    province, country, or other governmental
                                    jurisdiction where the data protection laws
                                    may differ from those of your jurisdiction.
                                </p>
                                <p>
                                    Your consent to this Privacy Policy followed
                                    by your submission of such information
                                    represents your agreement to that transfer.
                                    Fun Farming Uganda will take all steps
                                    reasonably necessary to ensure that your
                                    data is treated securely and in accordance
                                    with this Privacy Policy.
                                </p>

                                <h2>Data Deletion</h2>
                                <p>
                                    You have the right to delete or request that
                                    we assist in deleting the Personal Data that
                                    we have collected about you. You may request
                                    deletion of your data at any time by
                                    contacting us using the information below.
                                </p>
                                <p>
                                    Please note that we may need to retain
                                    certain information when we have a legal
                                    obligation or lawful basis to do so.
                                </p>

                                <h2>Disclosure of Data</h2>
                                <p>
                                    Fun Farming Uganda may disclose your
                                    Personal Data in the good faith belief that
                                    such action is necessary to:
                                </p>
                                <ul>
                                    <li>To comply with a legal obligation</li>
                                    <li>
                                        To protect and defend the rights or
                                        property of Fun Farming Uganda
                                    </li>
                                    <li>
                                        To prevent or investigate possible
                                        wrongdoing in connection with the
                                        service
                                    </li>
                                    <li>
                                        To protect the personal safety of users
                                        of the service or the public
                                    </li>
                                    <li>To protect against legal liability</li>
                                </ul>

                                <h2>Security of Data</h2>
                                <p>
                                    The security of your data is important to
                                    us. We implement appropriate technical and
                                    organizational measures to protect your
                                    personal information against unauthorized
                                    access, alteration, disclosure, or
                                    destruction. However, no method of
                                    transmission over the Internet or method of
                                    electronic storage is 100% secure. While we
                                    strive to use commercially acceptable means
                                    to protect your Personal Data, we cannot
                                    guarantee its absolute security.
                                </p>

                                <h2>Children&apos;s Privacy</h2>
                                <p>
                                    Our service is intended for use by
                                    individuals who are at least 18 years of
                                    age. We do not knowingly collect personally
                                    identifiable information from anyone under
                                    the age of 18. If you are a parent or
                                    guardian and you are aware that your child
                                    has provided us with Personal Data, please
                                    contact us. If we become aware that we have
                                    collected Personal Data from children
                                    without verification of parental consent, we
                                    take steps to remove that information from
                                    our servers.
                                </p>

                                <h2>Links to Other Sites</h2>
                                <p>
                                    Our service may contain links to other sites
                                    that are not operated by us. If you click on
                                    a third-party link, you will be directed to
                                    that third party&apos;s site. We strongly
                                    advise you to review the Privacy Policy of
                                    every site you visit.
                                </p>
                                <p>
                                    We have no control over and assume no
                                    responsibility for the content, privacy
                                    policies, or practices of any third-party
                                    sites or services.
                                </p>

                                <h2>Changes to This Privacy Policy</h2>
                                <p>
                                    We may update our Privacy Policy from time
                                    to time. We will notify you of any changes
                                    by posting the new Privacy Policy on this
                                    page and updating the &ldquo;effective
                                    date&rdquo; at the top of this page.
                                </p>
                                <p>
                                    You are advised to review this Privacy
                                    Policy periodically for any changes. Changes
                                    to this Privacy Policy are effective when
                                    they are posted on this page.
                                </p>

                                <h2>Contact Information</h2>
                                <p>
                                    If you have any questions about this Privacy
                                    Policy or our data practices, please contact
                                    us:
                                </p>
                                <ul>
                                    <li>
                                        Email: info@funfarminguganda.com
                                    </li>
                                    <li>
                                        Phone: +256 772 826 680 / +256 700 462
                                        477
                                    </li>
                                    <li>
                                        Address: Butalangu Town Council,
                                        Nakaseke District, Uganda
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}
