import Link from 'next/link';
import PageHeader from '@/components/sections/PageHeader';

export default function PrivacyPage() {
    return (
        <>
            <PageHeader
                title="Privacy Policy"
                bgImage="/assets/img/hero/about-us-inr-herothumb.png"
                breadcrumbs={[
                    { label: 'Home', href: '/' },
                    { label: 'Privacy' },
                ]}
            />

            <div className="vl-blog-details-area sp1">
                <div className="container">
                    <div className="row justify-content-center">
                        <div className="col-xl-8 col-lg-10">
                            <div className="vl-blog-details-content">
                                <p>
                                    <strong>
                                        Fun Farming Uganda (&ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;)
                                        operates the website funfarminguganda.com and provides agro-tourism, team-building,
                                        and farm experience services. This page informs you of our policies regarding the
                                        collection, use, and disclosure of personal data when you use our services.
                                    </strong>
                                </p>

                                <h2>Definitions</h2>
                                <p>
                                    <strong>Personal Data</strong> means data about a living individual who can be
                                    identified from those data (or from those and other information either in our
                                    possession or likely to come into our possession).
                                </p>
                                <p>
                                    <strong>Usage Data</strong> is data collected automatically, either generated by
                                    the use of the service or from the service infrastructure itself (for example, the
                                    duration of a page visit).
                                </p>
                                <p>
                                    <strong>Cookies</strong> are small pieces of data stored on your device (computer or
                                    mobile device).
                                </p>
                                <p>
                                    <strong>Data Controller</strong> means Fun Farming Uganda, which determines the
                                    purposes and means of the processing of your personal data.
                                </p>

                                <h2>Data Collection</h2>
                                <p>
                                    We collect several different types of information for various purposes to provide
                                    and improve our service to you.
                                </p>
                                <p>
                                    <strong>Personal Data:</strong> While using our service, we may ask you to provide us
                                    with certain personally identifiable information that can be used to contact or
                                    identify you. This includes your name, email address, phone number, physical address,
                                    and booking preferences.
                                </p>
                                <p>
                                    <strong>Usage Data:</strong> We may also collect information on how the service is
                                    accessed and used. This Usage Data may include your computer&apos;s Internet Protocol
                                    address (IP address), browser type, browser version, the pages of our service that you
                                    visit, the time and date of your visit, the time spent on those pages, unique device
                                    identifiers, and other diagnostic data.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    );
}