function Definitions() {
    return (
        <>
            <p>For the purposes of this Privacy Policy: </p>
            <ul>
                <li>
                    <strong>Account</strong> means a unique account created for
                    You to access our Service or parts of our Service.
                </li>
                <li>
                    <strong>Affiliate</strong> means an entity that controls, is
                    controlled by or is under common control with a party, where
                    &quot;control&quot; means ownership of 50% or more of the
                    shares or other securities entitled to vote.
                </li>
                <li>
                    <strong>Company</strong> (referred to as either &quot;the
                    Company&quot;, &quot;We&quot;, &quot;Us&quot; or
                    &quot;Our&quot; in this Agreement) refers to Fun Farming
                    Uganda, Butalangu Town Council, Nakaseke District,
                    Uganda.
                </li>
                <li>
                    <strong>Cookies</strong> are small files that are placed on
                    Your computer or mobile device by a website, containing the
                    details of Your browsing history.
                </li>
                <li>
                    <strong>Country</strong> refers to: Uganda.
                </li>
                <li>
                    <strong>Device</strong> means any device that can access the
                    Service such as a computer, a cellphone or a digital tablet.
                </li>
                <li>
                    <strong>Personal Data</strong> is any information that
                    relates to an identified or identifiable individual.
                </li>
                <li>
                    <strong>Service</strong> refers to the Website.
                </li>
                <li>
                    <strong>Service Provider</strong> means any natural or legal
                    person who processes the data on behalf of the Company.
                </li>
                <li>
                    <strong>Usage Data</strong> refers to data collected
                    automatically, either generated by the use of the Service or
                    from the Service infrastructure itself.
                </li>
                <li>
                    <strong>Website</strong> refers to Fun Farming Uganda,
                    accessible from{' '}
                    <a
                        href="https://funfarminguganda.com"
                        rel="external nofollow noopener"
                        target="_blank"
                    >
                        https://funfarminguganda.com
                    </a>
                </li>
                <li>
                    <strong>You</strong> means the individual accessing or using
                    the Service.
                </li>
            </ul>
        </>
    );
}

function PersonalDataSection() {
    return (
        <>
            <h3>Types of Data Collected</h3>
            <h4>Personal Data</h4>
            <p>
                While using Our Service, We may ask You to provide Us with
                certain personally identifiable information that can be used to
                contact or identify You. This may include, but is not limited
                to:
            </p>
            <ul>
                <li>Email address</li>
                <li>First name and last name</li>
                <li>Phone number</li>
                <li>Usage Data</li>
            </ul>
            <h4>Usage Data</h4>
            <p>
                Usage Data is collected automatically when using the Service. It
                may include information such as Your Device's Internet Protocol
                address, browser type, browser version, the pages of our Service
                that You visit, the time and date of Your visit and other
                diagnostic data.
            </p>
            <h4>Tracking Technologies and Cookies</h4>
            <p>
                We use Cookies and similar tracking technologies to track the
                activity on Our Service and store certain information. The
                technologies We use may include:
            </p>
            <ul>
                <li>
                    {' '}
                    <strong>Cookies or Browser Cookies.</strong> A cookie is a
                    small file placed on Your Device. You can instruct Your
                    browser to refuse all Cookies or to indicate when a Cookie
                    is being sent.{' '}
                </li>
                <li>
                    {' '}
                    <strong>Web Beacons.</strong> Certain sections of our
                    Service and our emails may contain small electronic files
                    known as web beacons that permit the Company to count users
                    and for other related website statistics.{' '}
                </li>
            </ul>
            <p>
                Cookies can be &quot;Persistent&quot; or &quot;Session&quot;
                Cookies. We use both Session and Persistent Cookies for
                necessary and essential purposes, cookie policy acceptance and
                functionality.
            </p>
            <h3>Use of Your Personal Data</h3>
            <p>
                The Company may use Personal Data for the following
                purposes:{' '}
            </p>
            <ul>
                <li>
                    To provide and maintain our Service, including monitoring
                    usage.
                </li>
                <li>To manage Your Account registration.</li>
                <li>For the performance of a contract with You.</li>
                <li>
                    To contact You by email, telephone calls, SMS or other
                    equivalent forms of communication.
                </li>
                <li>
                    To provide You with news, special offers and general
                    information about other goods, services and events.
                </li>
                <li>To manage Your requests to Us.</li>
                <li>
                    For business transfers, such as a merger or sale of assets.
                </li>
            </ul>
            <p>
                We may share Your personal information with Service Providers,
                in connection with business transfers, with affiliates, business
                partners and other users, or with Your consent.
            </p>
            <h3>Retention of Your Personal Data</h3>
            <p>
                The Company will retain Your Personal Data only for as long as
                is necessary for the purposes set out in this Privacy Policy,
                and to the extent necessary to comply with our legal
                obligations, resolve disputes and enforce our policies.
            </p>
            <h3>Transfer of Your Personal Data</h3>
            <p>
                Your information is processed at the Company's operating
                offices, which may be located outside Your state or country
                where data protection laws may differ. We will take all steps
                reasonably necessary to ensure that Your data is treated
                securely.
            </p>
            <h3>Delete Your Personal Data</h3>
            <p>
                You have the right to delete or request that We assist in
                deleting the Personal Data that We have collected about You. You
                may also request access to, correct, or delete any personal
                information that You have provided to Us.
            </p>
            <h3>Disclosure of Your Personal Data</h3>
            <p>
                In the event of a merger, acquisition or asset sale, or where
                required by law or in response to valid requests by public
                authorities, the Company may disclose Your Personal Data in the
                good faith belief that such action is necessary to comply with a
                legal obligation, protect and defend the rights of the Company,
                prevent possible wrongdoing, protect public safety, and protect
                against legal liability.
            </p>
            <h3>Security of Your Personal Data</h3>
            <p>
                The security of Your Personal Data is important to Us, but
                remember that no method of transmission over the Internet is
                100% secure. While we strive to use commercially acceptable
                means to protect Your Personal Data, we cannot guarantee its
                absolute security.
            </p>
        </>
    );
}

export function PrivacyPage() {
    return (
        <div className="main-content pb-0 pt-93">
            <section className="s-terms">
                <div className="tf-container w-1290">
                    <div className="row">
                        <div className="col-lg-12">
                            <div className="content-box">
                                <div className="heading-section style-4 mb-30">
                                    <div className="img-item">
                                        <p className="sub-title">
                                            Privacy Policy
                                        </p>
                                        <p className="title text-anime-style-1">
                                            Your Data Matters To Us
                                        </p>
                                    </div>
                                </div>
                                <p>Last updated: August 03, 2026</p>
                                <p>
                                    This Privacy Policy describes our policies
                                    and procedures on the collection, use and
                                    disclosure of Your information when You use
                                    the Service, and tells You about Your
                                    privacy rights and how the law protects You.
                                </p>
                                <p>
                                    We use Your Personal data to provide and
                                    improve the Service. By using the Service,
                                    You agree to the collection and use of
                                    information in accordance with this Privacy
                                    Policy.
                                </p>

                                <h2>Interpretation and Definitions</h2>
                                <h3>Interpretation</h3>
                                <p>
                                    The words of which the initial letter is
                                    capitalized have meanings defined under the
                                    following conditions. The following
                                    definitions shall have the same meaning
                                    regardless of whether they appear in
                                    singular or in plural.
                                </p>
                                <h3>Definitions</h3>
                                <Definitions />

                                <h2>Collecting and Using Your Personal Data</h2>
                                <PersonalDataSection />

                                <h2>Children's Privacy</h2>
                                <p>
                                    Our Service does not address anyone under
                                    the age of 13. We do not knowingly collect
                                    personally identifiable information from
                                    anyone under the age of 13. If You are a
                                    parent or guardian and You are aware that
                                    Your child has provided Us with Personal
                                    Data, please contact Us.
                                </p>

                                <h2>Links to Other Websites</h2>
                                <p>
                                    Our Service may contain links to other
                                    websites that are not operated by us. We
                                    strongly advise You to review the Privacy
                                    Policy of every site You visit.
                                </p>

                                <h2>Changes to this Privacy Policy</h2>
                                <p>
                                    We may update Our Privacy Policy from time
                                    to time. We will notify You of any changes
                                    by posting the new Privacy Policy on this
                                    page and update the &quot;Last updated&quot;
                                    date.
                                </p>

                                <h2>Contact Us</h2>
                                <p>
                                    If you have any questions about this Privacy
                                    Policy, You can contact us by email at{' '}
                                    <a href="mailto:support@funfarminguganda.com">
                                        support@funfarminguganda.com
                                    </a>
                                    .
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    );
}
