'use client';

import Script from 'next/script';

export default function ClientLayoutScripts() {
    return (
        <>
            <Script
                src="/assets/vendors/jquery/jquery-3.7.1.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/bootstrap/js/bootstrap.bundle.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/bootstrap-select/bootstrap-select.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jarallax/jarallax.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jquery-ui/jquery-ui.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jquery-ajaxchimp/jquery.ajaxchimp.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jquery-appear/jquery.appear.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jquery-circle-progress/jquery.circle-progress.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jquery-magnific-popup/jquery.magnific-popup.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/jquery-validate/jquery.validate.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/nouislider/nouislider.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/tiny-slider/tiny-slider.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/wnumb/wNumb.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/owl-carousel/js/owl.carousel.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/wow/wow.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/imagesloaded/imagesloaded.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/isotope/isotope.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/slick/slick.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/tilt/tilt.jquery.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/countdown/countdown.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/gsap/gsap.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/gsap/ScrollTrigger.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/gsap/splittext.min.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/gsap/scroll-smoother.js"
                strategy="afterInteractive"
            />
            <Script
                src="/assets/vendors/gsap/garlon-split.js"
                strategy="afterInteractive"
            />
            <Script src="/assets/js/garlon.js" strategy="afterInteractive" />
        </>
    );
}
